# GAME SETTINGS
NEURAL_NETWORK_WINDOW_SIZE = 600
GAME_WINDOW_SIZE = 700
INFO_WINDOW_SIZE = 215
FRAME_RATE = 30
BLOCK_SIZE = 10
NODE_SIZE = 11
NODE_SPACING = NODE_SIZE * 2 + 4
# 2 < MAP_SIZE <= 70
MAP_SIZE = 50

# NEURAL NETWORK
HIDDEN_LAYERS = (18, )
INPUT_LAYER = 24
OUTPUT_LAYER = 4

# GENETIC ALGORITHM
POPULATION_SIZE = 2000
MUTATION_RATE = 0.1
MOVES_LEFT = MAP_SIZE * 10
MOVES_UPPER_BOUND = 3

# CONSTANTS
FONT = "freesansbold.ttf"
FONT_SIZE = 15
OFFSET = (GAME_WINDOW_SIZE - MAP_SIZE * BLOCK_SIZE) / 2
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
